name: Run test suite

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install test dependencies
        run: |
          pip install .
          pip install -r requirements_test.txt
      - name: Run the tests
        run: |
          pytest
